#!/usr/bin/env sh

# The "Postprocessor" line displays processing time -- see the log
sed '/version/Id' $1 | sed '/using watermask/d' > tmplog1
sed '/version/Id' $2 | sed '/using watermask/d' > tmplog2

diff tmplog1 tmplog2
retval=$?

rm tmplog1 tmplog2

echo "log_diff returning $retval"

exit $retval
