#!/usr/bin/env sh

# The "Postprocessor" line displays processing time -- see the log
sed '/version/Id' $1 | sed '/PRODUCT_CREATION_DATE/d' | sed '/DATE_TIME/d' > tmplog1
sed '/version/Id' $2 | sed '/PRODUCT_CREATION_DATE/d' | sed '/DATE_TIME/d' > tmplog2

diff tmplog1 tmplog2
retval=$?

rm tmplog1 tmplog2

echo "log_diff returning $retval"

exit $retval
