# Makefile generated by imake - do not edit!

 #***********************************************************************
 #
 # This makefile is automatically generated by imake.  If you need to change
 # the makefile, edit the .imake file and re-run imake, or contact the VICAR
 # system programmer to change the imake templates.
 #
 # *** DO NOT EDIT THIS FILE!! ***
 #
 #***********************************************************************

 #

UNIT_NAME = obj2plane
 # VICAR program obj2plane

 #
 #***********************************************************************

CCC = g++

SHELL = /bin/sh
CP = cp
CHMOD_X = chmod +x

AR = ar r

ARX = ar x

RM = rm -f

LN = ln -fs

RANLIB = ranlib

RUN_TM  = taetm
MSGBLD  = $$TAEPDF/msgbld

LINK.ccc = $(CCC)  $(CCCFLAGS) $(CPPFLAGS) $(LDFLAGS)

.cc.o:
	$(CCC) $(CCCFLAGS) $(CPPFLAGS) -c  $<

LDFLAGS =

CCCFLAGS = -O      -Wno-implicit -Wno-invalid-offsetof -Wno-write-strings  -ffriend-injection

CPPFLAGS =  -I$(V2INC) -I$(TAEINC)    -I$(P1INC)     -I$(P2INC) -I$(P2GENINC)                                    -I$(EIGEN_LIB)                 -I$(TINYOBJLOADER_LIB)

OBJS = obj2plane.o

INCLUDES =

CLEANOBJS = obj2plane.o

CLEANSRC = obj2plane.cc

CLEANOTHER =

CLEANINC =

 # Note that SYSTEMINC is used only for includes that are installed,
 # e.g. from a TAO/IDL build.

LIBS = -L$(V2OLB)               -lp2sub    -lp1sub                                            $(V2OLB)/librtl.a  -lshvic    -L$(TAELIB) $(TAELIB)/libtaec.o  -ltae -lncurses             -lm

std: obj2plane

all: obj2plane doc

system: obj2plane doc clean.obj clean.src

compile:  $(OBJS)

obj2plane:  $(OBJS)
	$(LINK.ccc) -o obj2plane $(OBJS) $(LIBS)

doc:

clean.obj:
	-$(RM) $(CLEANOBJS)

clean.src:
	-$(RM) $(CLEANSRC) $(CLEANINC) $(CLEANOTHER)
	-$(RM) $(UNIT_NAME).make $(UNIT_NAME).bld $(UNIT_NAME).imake

$(OBJS): $(INCLUDES)

