CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Close the polygon
C
      SUBROUTINE CLOSE_POL(IPOL,XYA,IVBUF,IVPTR,XYBUF,NVERT2,ZINGER,GR1)
      IMPLICIT NONE
      INTEGER*4 IPOL,NVERT2
      INTEGER*4 IVBUF(1),IVPTR(1)
      INTEGER*2 XYA(2,1),XYBUF(2,1)
      LOGICAL ZINGER,GR1

      COMMON/CSAVE/IEDGE,ISLCNT,IPVCNT,IPPCNT,LVPTR,IPCNT,IPCNT0
      INTEGER*4 IEDGE,ISLCNT,IPVCNT,IPPCNT,LVPTR,IPCNT,IPCNT0

      INTEGER I,IPTR,N,IX,IY,IV,JJX,JJY
      REAL*4 X,Y,XMIN,YMIN,XMAX,YMAX,XCENTR,YCENTR

      LOGICAL BORDRX,BORDRY,OUTSID

      XMIN = 1.E10
      YMIN = 1.E10
      XMAX = 0.
      YMAX = 0.
      XCENTR = 0
      YCENTR = 0
      IF (ZINGER) IPCNT0=IPCNT

      DO 60 I=1,IPCNT
      IPTR = IVPTR(I)
      IV = IVBUF(IPTR)
      IV = IABS(IV)
      IX = XYA(1,IV)
      IY = XYA(2,IV)
      X = IX
      Y = IY
      XYBUF(1,I) = IX
      XYBUF(2,I) = IY
      IF (I.GT.IPCNT0) GOTO 60
      XCENTR = XCENTR+X
      YCENTR = YCENTR+Y
      XMIN = AMIN1(XMIN,X)
      YMIN = AMIN1(YMIN,Y)
      XMAX = AMAX1(XMAX,X)
      YMAX = AMAX1(YMAX,Y)
      CALL OPVR(X,Y,NVERT2,GR1)
   60 CONTINUE

      CALL OPVR(-.01,-.01,NVERT2,GR1)	!end-of-polygon marker
      XCENTR = (XCENTR-X)/(IPCNT0-1)
      YCENTR = (YCENTR-Y)/(IPCNT0-1)
      DO N=1,2
         CALL MOVCEN(XYBUF,1,2,XCENTR,YCENTR,IPCNT,JJY,BORDRY,OUTSID)
         CALL MOVCEN(XYBUF,2,1,YCENTR,XCENTR,IPCNT,JJX,BORDRX,OUTSID)
      ENDDO
      CALL OPHDR(ISLCNT,IPCNT0,XMIN,XMAX,YMIN,YMAX,XCENTR,YCENTR,IPOL)
      END
