CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Check if centroid is inside.
C
      SUBROUTINE MOVCEN(XYBUF,IX1,IX2,XCENTR,YCENTR,NVRT,
     +		JJ,BORDER,OUTSID)
      IMPLICIT NONE
      REAL*4 XCENTR,YCENTR
      INTEGER*4 IX1,IX2,NVRT,JJ
      LOGICAL BORDER,OUTSID
      INTEGER*2 XYBUF(2,1)

      INTEGER*4 I,I1,J1,J2
      REAL*4 X1,Y1,X2,Y2,Y0,Z,EPS
      REAL*4 YCROS1(2), YCROS2(2)

C       ! ( CONVERSION NOTE: EPS IS AN UNDEFINED VARIABLE?  NO MATTER, 
C       !   SINCE BORDER IS IGNORED BY CALLING SUBROUTINE. )

      J1 = 0
      J2 = 0
      BORDER = .FALSE.
      OUTSID = .FALSE.
      X1 = XYBUF(IX1,1)
      Y1 = XYBUF(IX2,1)

      DO 25 I=1,NVRT
      I1 = I + 1
      IF (I.EQ.NVRT) I1=1
      X2 = XYBUF(IX1,I1)
      Y2 = XYBUF(IX2,I1)
      IF ((XCENTR-X1)*(X2-XCENTR).LE.0) GO TO 20
      Y0  =  Y1+(Y2-Y1)/(X2-X1)*(XCENTR-X1)
CCC         IF (X1.EQ.X2) Y0  =  (Y1+Y2)/2.
      IF (ABS(Y0-YCENTR).LT.EPS) BORDER=.TRUE.
      Z = ABS(Y0-YCENTR)
      IF (Y0.LT.YCENTR) THEN
         J2 = J2+1
         IF (J2.EQ.1 .OR. J2.EQ.2) YCROS2(J2)=Y0
      ELSE
         J1 = J1+1
         IF (J1.EQ.1 .OR. J1.EQ.2) YCROS1(J1)=Y0
      ENDIF
   20 X1 = X2
      Y1 = Y2
   25 CONTINUE

      IF (J1-J1/2*2.EQ.0.AND.J2-J2/2*2.EQ.0) JJ=JJ+1
      IF (J1-J1/2*2.NE.0.OR.J1.EQ.0) GOTO 30
      YCENTR = (YCROS1(1)+YCROS1(2))/2.
      IF (ABS(YCROS1(1)-YCROS1(2)).LT.2*EPS) BORDER=.TRUE.
      GOTO 40

   30 IF (J2-J2/2*2.NE.0.OR.J2.EQ.0) GOTO 40
      YCENTR = (YCROS2(1)+YCROS2(2))/2.
      IF (ABS(YCROS2(1)-YCROS2(2)).LT.2*EPS) BORDER=.TRUE.

   40 IF (J1.EQ.0.AND.J2.EQ.0) OUTSID=.TRUE.
      IF (J1+J2-(J1+J2)/2*2.NE.0) OUTSID=.TRUE.
      RETURN
      END
