CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Write edge header record (currently a dummy routine)
C
      SUBROUTINE OEHDR(IEDGE,LCLAS,LPOLY,LAREA,IRCLAS,IRPOLY,
     +                 IRAREA,NPTS,ODSRN)
      INTEGER*4 ODSRN
      RETURN
      END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Write edge vertex record (currently a dummy routine)
C
      SUBROUTINE OEVR(IX,IY,ODSRN)
      INTEGER*4 ODSRN
      RETURN
      END
