CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Copy polygon vertex to VERTICES.
C
      SUBROUTINE OPVR(X,Y,NVERT2,GR1)
      IMPLICIT NONE
      REAL*4 X,Y	!graphics coordinates
      INTEGER*4 NVERT2
      LOGICAL GR1

      COMMON/FILES/INFILE,LABELEDF,POLYDESF,SERLFILE,VERTICES,POLYINFO
      INTEGER*4 INFILE,LABELEDF,POLYDESF,SERLFILE,VERTICES,POLYINFO

      COMMON/IBIS_FILES/IBIS_PD,IBIS_S,IBIS_V,IBIS_PI
      INTEGER*4 IBIS_PD,IBIS_S,IBIS_V,IBIS_PI

      COMMON/IBIS_RECORDS/PD_REC,SERL_REC,V_REC,PI_REC
      INTEGER*4 PD_REC,SERL_REC,V_REC,PI_REC

      COMMON/CMAX/MAXPOLY,MAXVERT
      INTEGER MAXPOLY,MAXVERT

      INTEGER*4 STATUS
      REAL*4 RB(2)

      RB(1) = Y + 0.01
      RB(2) = X + 0.01
      IF (GR1) THEN
         CALL PUTGR(VERTICES,RB(1),RB(2))	!output is graphics 1 format
         RETURN
      ENDIF

C     ....Here if output is IBIS2 format
      NVERT2 = NVERT2 + 1
      IF (NVERT2.GT.MAXVERT) THEN
         MAXVERT = 1.5*MAXVERT
         CALL IBIS_FILE_SET(IBIS_V,'NR',MAXVERT,STATUS)
         IF (STATUS.NE.1) CALL IBIS_SIGNAL(IBIS_V,STATUS,1)
         CALL XVMESSAGE('OPVR increased MAXVERT',' ')
      ENDIF
      CALL IBIS_RECORD_WRITE(V_REC,RB,NVERT2,STATUS)
      IF (STATUS.NE.1) CALL IBIS_SIGNAL(IBIS_V,STATUS,1)
      RETURN
      END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Routine to write polygon data to POLYINFO row
C
      SUBROUTINE OPHDR(ISLCNT,NPTS,XMIN,XMAX,YMIN,YMAX,
     *                 XCENTR,YCENTR,IPOL)
      IMPLICIT NONE
      INTEGER*4 ISLCNT,NPTS,IPOL
      REAL*4 XMIN,XMAX,YMIN,YMAX,XCENTR,YCENTR

      COMMON/IBIS_FILES/IBIS_PD,IBIS_S,IBIS_V,IBIS_PI
      INTEGER*4 IBIS_PD,IBIS_S,IBIS_V,IBIS_PI

      COMMON/IBIS_RECORDS/PD_REC,SERL_REC,V_REC,PI_REC
      INTEGER*4 PD_REC,SERL_REC,V_REC,PI_REC

      INTEGER*4 STATUS,ICLAS,IAREA
      REAL*4 SB(10)

      CALL GET_POLYGON(IPOL,iclas,iarea)

      SB(1) = ISLCNT
      SB(2) = NPTS
      SB(3) = ICLAS
      SB(4) = XMIN
      SB(5) = XMAX
      SB(6) = YMIN
      SB(7) = YMAX
      SB(8) = XCENTR
      SB(9) = YCENTR
      SB(10) = IAREA
      CALL IBIS_RECORD_WRITE(PI_REC,SB,IPOL,STATUS)
      IF (STATUS.NE.1) CALL IBIS_SIGNAL(IBIS_PI,STATUS,1)
      RETURN
      END
